#存放公用配置
spring:
  profiles:
    active: @env@
mybatis-plus:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml
  type-aliases-package: com.company.project.biz.entity
  global-config:
    db-config:
      id-type: auto
app:
  id: sentinel-test
apollo:
  bootstrap:
    enabled: true
#ywwl:
#  sentinel:
#    transport:
#      dashboard: 192.168.202.83:8080