#开发环境配置
spring:
  profiles:
    active: rd
  #数据源配置
  datasource:
    url: jdbc:mysql://172.16.5.163/trial?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&autoReconnect=true&failOverReadOnly=false&amp;allowMultiQueries=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  #redis配置
  redis:
    host:
    password:
    port: 6379
    database: 0
    pool:
      max-active: 50
      max-idle: 20
      max-wait: -1
      min-idle: 10
    timeout: 10000
#开发环境打印sql
logging:
  level:
    com.company.project.biz.mapper: debug
app:
  id: sentinel
apollo:
  bootstrap:
    enabled: true
    namespaces: application
